version: '3.3'
volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_HOST
      - DB_PORT
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: tiaki2601/foodgram_backend:latest
    env_file: .env
    environment:
      - ALLOWED_HOSTS
      - SECRET_KEY
      - DEBUG
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
  
  frontend:
    image: tiaki2601/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: tiaki2601/foodgram_nginx:latest
    env_file: .env
    environment:
      - ALLOWED_HOSTS
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../backend/docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend
