# Generated by Django 4.2.4 on 2023-09-08 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountrecipeingredients',
            options={'ordering': ['recipe'], 'verbose_name': 'Количество ингредиентов в рецепте', 'verbose_name_plural': 'Количество ингредиентов в рецептах'},
        ),
        migrations.RemoveConstraint(
            model_name='amountrecipeingredients',
            name='unique_ingredients',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_for_ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_for_author',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping',
        ),
        migrations.AlterUniqueTogether(
            name='amountrecipeingredients',
            unique_together={('recipe', 'ingredients')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'recipe')},
        ),
    ]
