# Generated by Django 4.2.4 on 2023-10-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmountRecipeIngredients',
            new_name='AmountRecipeIngredient',
        ),
    ]
