# Generated by Django 4.2.4 on 2023-09-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_amountrecipeingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountrecipeingredients',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Наименование ингредиентов'),
        ),
        migrations.AlterField(
            model_name='amountrecipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Наименование рецептов'),
        ),
    ]
